server:
  port: 8082

spring:
  application:
    name: currency-api
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redispswd
      connect-timeout: 2000ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:currency_service}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:pswd}

  jpa:
    show-sql: true

logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR
    org.springframework.validation: DEBUG
    org.springframework.web: DEBUG